# Generated by Django 5.1.1 on 2024-10-05 12:04

import colorfield.fields
import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('wms', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Color',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('color', colorfield.fields.ColorField(default='#FF0000', image_field=None, max_length=25, samples=None)),
                ('name', models.CharField(max_length=50, verbose_name='Названия')),
            ],
            options={
                'verbose_name': 'Цвет',
                'verbose_name_plural': 'Цвет',
            },
        ),
        migrations.CreateModel(
            name='Stage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Название этапа')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Порядок в тех. процессе')),
            ],
            options={
                'verbose_name': 'Этапы',
                'verbose_name_plural': 'Этапы',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='ProductionItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Название')),
                ('image', models.ImageField(blank=True, null=True, upload_to='product_images/', verbose_name='Фотография')),
                ('article', models.CharField(blank=True, max_length=50, verbose_name='Артикул')),
                ('design_description', models.TextField(blank=True, verbose_name='Описание дизайна')),
                ('size', models.CharField(max_length=255, verbose_name='Размеры')),
                ('batch_number', models.CharField(blank=True, max_length=50, verbose_name='Номер партии')),
                ('_cost_price', models.DecimalField(decimal_places=2, default=0, editable=False, max_digits=10, verbose_name='Себестоимость')),
                ('color', models.ManyToManyField(to='production.color')),
            ],
            options={
                'verbose_name': 'Карточка модели',
                'verbose_name_plural': 'Карточка модели',
            },
        ),
        migrations.CreateModel(
            name='Operation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Название операции')),
                ('description', models.TextField(blank=True, verbose_name='Описание')),
                ('stage', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='production.stage', verbose_name='Этап производства')),
            ],
            options={
                'verbose_name': 'Операции',
                'verbose_name_plural': 'Операции',
            },
        ),
        migrations.CreateModel(
            name='TechnologicalMap',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Название карты')),
                ('description', models.TextField(blank=True, verbose_name='Описание')),
                ('production_item', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='technological_map', to='production.productionitem', verbose_name='Изделие')),
            ],
            options={
                'verbose_name': 'Технологическая карта',
                'verbose_name_plural': 'Технологическая карта',
            },
        ),
        migrations.CreateModel(
            name='TechnologicalMapMaterial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(0.01)], verbose_name='Количество')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='wms.product', verbose_name='Материал')),
                ('stock', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='wms.warehouse', verbose_name='Склад')),
                ('technological_map', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='materials', to='production.technologicalmap', verbose_name='Технологическая карта')),
            ],
            options={
                'verbose_name': 'Тех карта материала',
                'verbose_name_plural': 'Тех карта материала',
            },
        ),
        migrations.CreateModel(
            name='TechnologicalMapOperation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('piece_rate', models.DecimalField(decimal_places=2, default=0, max_digits=8, verbose_name='Ставка за штуку')),
                ('time_norm', models.PositiveIntegerField(default=0, verbose_name='Норма времени (мин)')),
                ('unit', models.CharField(default='шт', max_length=50, verbose_name='Единица измерения')),
                ('details_quantity_per_product', models.PositiveIntegerField(default=0, verbose_name='Количество деталей на одно изделие')),
                ('operation', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='production.operation', verbose_name='Операция')),
                ('technological_map', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='operation', to='production.technologicalmap', verbose_name='Технологическая карта')),
            ],
            options={
                'verbose_name': 'Тех карта операции',
                'verbose_name_plural': 'Тех карта операции',
            },
        ),
    ]
