# Generated by Django 5.1.1 on 2024-09-18 09:13

import datetime
import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('manufactory', '0001_initial'),
        ('order', '0001_initial'),
        ('wms', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductionItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Название')),
                ('article', models.CharField(blank=True, max_length=50, verbose_name='Артикул')),
                ('design_description', models.TextField(blank=True, verbose_name='Описание дизайна')),
                ('size', models.CharField(max_length=255, verbose_name='Размеры')),
                ('color', models.CharField(max_length=50, verbose_name='Цвет')),
                ('batch_number', models.CharField(blank=True, max_length=50, verbose_name='Номер партии')),
            ],
        ),
        migrations.CreateModel(
            name='ProductionOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('planned_completion_date', models.DateField(verbose_name='Планируемая дата завершения')),
                ('actual_completion_date', models.DateField(blank=True, null=True, verbose_name='Фактическая дата завершения')),
                ('priority', models.CharField(choices=[('high', 'Высокий'), ('medium', 'Средний'), ('low', 'Низкий')], default='medium', max_length=10, verbose_name='Приоритет')),
                ('status', models.CharField(choices=[('new', 'Новый'), ('in_progress', 'В производстве'), ('completed', 'Завершен'), ('canceled', 'Отменен')], default='new', max_length=20, verbose_name='Статус')),
                ('notes', models.TextField(blank=True, verbose_name='Заметки')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='order.order', verbose_name='Заказ клиента')),
            ],
        ),
        migrations.CreateModel(
            name='TechnologicalMap',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.DecimalField(decimal_places=2, default=1, max_digits=10000, verbose_name='Количество изделии')),
                ('name', models.CharField(max_length=255, verbose_name='Название карты')),
                ('description', models.TextField(blank=True, verbose_name='Описание')),
                ('production_item', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='technological_map', to='production.productionitem', verbose_name='Изделие')),
            ],
        ),
        migrations.CreateModel(
            name='TechnologicalMapEquipment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('equipment', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='manufactory.equipment', verbose_name='Оборудование')),
                ('technological_map', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='technological_map_equipments', to='production.technologicalmap', verbose_name='Технологическая карта')),
            ],
        ),
        migrations.CreateModel(
            name='TechnologicalMapMaterial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(0.01)], verbose_name='Количество')),
                ('category', models.ForeignKey(default=0, on_delete=django.db.models.deletion.PROTECT, to='wms.productcategory', verbose_name='Категория')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='wms.product', verbose_name='Материал')),
                ('technological_map', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='technological_map_materials', to='production.technologicalmap', verbose_name='Технологическая карта')),
            ],
        ),
        migrations.CreateModel(
            name='TechnologicalMapOperation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sequence', models.PositiveIntegerField(default=1, verbose_name='Порядок операции')),
                ('norm_time', models.DurationField(validators=[django.core.validators.MinValueValidator(datetime.timedelta(seconds=1))], verbose_name='Норма времени')),
                ('piecework_rate', models.DecimalField(blank=True, decimal_places=2, help_text='Укажите ставку, если оплата сдельная', max_digits=8, null=True, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Сдельная ставка (за штуку)')),
                ('operation', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='manufactory.operation', verbose_name='Операция')),
                ('technological_map', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='technological_map_operations', to='production.technologicalmap', verbose_name='Технологическая карта')),
            ],
        ),
    ]
