# Generated by Django 5.1.1 on 2024-09-18 12:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('production', '0001_initial'),
        ('wms', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='technologicalmap',
            name='quantity',
        ),
        migrations.RemoveField(
            model_name='technologicalmapoperation',
            name='norm_time',
        ),
        migrations.RemoveField(
            model_name='technologicalmapoperation',
            name='piecework_rate',
        ),
        migrations.AddField(
            model_name='productionorder',
            name='warehouse',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='wms.warehouse', verbose_name='Склад'),
        ),
        migrations.DeleteModel(
            name='TechnologicalMapEquipment',
        ),
    ]
