# Generated by Django 5.1.1 on 2024-09-19 07:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manufactory', '0005_brigade_operationlog_and_more'),
        ('production', '0002_remove_technologicalmap_quantity_and_more'),
        ('wms', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Operation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Название операции')),
                ('description', models.TextField(blank=True, verbose_name='Описание')),
            ],
        ),
        migrations.CreateModel(
            name='Stage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Название этапа')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Порядок в тех. процессе')),
            ],
            options={
                'ordering': ['order'],
            },
        ),
        migrations.RemoveField(
            model_name='technologicalmapmaterial',
            name='category',
        ),
        migrations.RemoveField(
            model_name='technologicalmapoperation',
            name='sequence',
        ),
        migrations.AddField(
            model_name='technologicalmapmaterial',
            name='stock',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='wms.stock', verbose_name='Склад'),
        ),
        migrations.AddField(
            model_name='technologicalmapoperation',
            name='details_quantity_per_product',
            field=models.PositiveIntegerField(default=0, verbose_name='Количество деталей на одно изделие'),
        ),
        migrations.AddField(
            model_name='technologicalmapoperation',
            name='piece_rate',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=8, verbose_name='Ставка за штуку'),
        ),
        migrations.AddField(
            model_name='technologicalmapoperation',
            name='time_norm',
            field=models.PositiveIntegerField(default=0, verbose_name='Норма времени (мин)'),
        ),
        migrations.AddField(
            model_name='technologicalmapoperation',
            name='unit',
            field=models.CharField(default='шт', max_length=50, verbose_name='Единица измерения'),
        ),
        migrations.AlterField(
            model_name='technologicalmapmaterial',
            name='technological_map',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='materials', to='production.technologicalmap', verbose_name='Технологическая карта'),
        ),
        migrations.AlterField(
            model_name='technologicalmapoperation',
            name='technological_map',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='operation', to='production.technologicalmap', verbose_name='Технологическая карта'),
        ),
        migrations.AlterField(
            model_name='technologicalmapoperation',
            name='operation',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='production.operation', verbose_name='Операция'),
        ),
        migrations.AddField(
            model_name='operation',
            name='stage',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='production.stage', verbose_name='Этап производства'),
        ),
        migrations.DeleteModel(
            name='ProductionOrder',
        ),
    ]
