# Generated by Django 5.1.1 on 2024-09-19 08:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('production', '0003_operation_stage_and_more'),
        ('wms', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='technologicalmapmaterial',
            name='stock',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='wms.warehouse', verbose_name='Склад'),
        ),
    ]
