# Generated by Django 5.1.1 on 2024-09-19 11:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('production', '0004_alter_technologicalmapmaterial_stock'),
    ]

    operations = [
        migrations.AddField(
            model_name='productionitem',
            name='cost_price',
            field=models.DecimalField(decimal_places=2, default=0, editable=False, max_digits=10, verbose_name='Себестоимость'),
        ),
    ]
