# Generated by Django 5.1.1 on 2024-09-19 11:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('production', '0005_productionitem_cost_price'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productionitem',
            name='cost_price',
        ),
        migrations.AddField(
            model_name='technologicalmap',
            name='cost_price',
            field=models.DecimalField(decimal_places=2, default=0, editable=False, max_digits=10, verbose_name='Себестоимость'),
        ),
    ]
