# Generated by Django 5.1.1 on 2024-09-25 11:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('production', '0007_remove_technologicalmap_cost_price_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='productionitem',
            old_name='cost_price',
            new_name='_cost_price',
        ),
    ]
