# Generated by Django 5.1.1 on 2024-09-29 09:24

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('HRM', '__first__'),
        ('order', '0001_initial'),
        ('production', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Assignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateTimeField(blank=True, null=True, verbose_name='Дата начала')),
                ('end_date', models.DateTimeField(blank=True, null=True, verbose_name='Дата окончания')),
                ('status', models.CharField(choices=[('new', 'Новое'), ('in_progress', 'В работе'), ('completed', 'Выполнено'), ('paused', 'Приостановлено')], default='new', max_length=20, verbose_name='Статус')),
                ('order', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='order.order', verbose_name='Заказ')),
            ],
            options={
                'verbose_name': 'Заказ на производство',
                'verbose_name_plural': 'Заказ на производство',
            },
        ),
        migrations.CreateModel(
            name='Cutting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(verbose_name='Количество')),
                ('map', models.CharField(max_length=255, verbose_name='Карта')),
                ('assignment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='manufactory.assignment', verbose_name='Задание')),
                ('order_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='order.orderitem', verbose_name='Позиция заказа')),
            ],
            options={
                'verbose_name': 'Крой',
                'verbose_name_plural': 'Крой',
            },
        ),
        migrations.CreateModel(
            name='Defect',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(verbose_name='Количество  бракованных  изделий')),
                ('description', models.TextField(blank=True, verbose_name='Описание  брака')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата  создания')),
                ('assignment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='manufactory.assignment', verbose_name='Задание')),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='HRM.sewing', verbose_name='Сотрудник')),
                ('operation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='production.technologicalmapoperation', verbose_name='Операция')),
            ],
            options={
                'verbose_name': 'Брак',
                'verbose_name_plural': 'Брак',
            },
        ),
        migrations.CreateModel(
            name='MaterialRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('requested_quantity', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Запрошенное количество')),
                ('issued_quantity', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Выданное количество')),
                ('status', models.CharField(choices=[('requested', 'Запрошено'), ('partially_issued', 'Частично выдано'), ('issued', 'Выдано'), ('canceled', 'Отменено')], default='requested', max_length=20, verbose_name='Статус')),
                ('assignment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='manufactory.assignment', verbose_name='Задание')),
                ('material', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='production.technologicalmapmaterial', verbose_name='Материал')),
            ],
            options={
                'verbose_name': 'Заявка на материал',
                'verbose_name_plural': 'Заявки на материалы',
            },
        ),
        migrations.CreateModel(
            name='OperationLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(verbose_name='Количество')),
                ('start_time', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Время начала')),
                ('end_time', models.DateTimeField(blank=True, null=True, verbose_name='Время окончания')),
                ('duration', models.DurationField(blank=True, null=True, verbose_name='Длительность')),
                ('defect_quantity', models.PositiveIntegerField(default=0, verbose_name='Количество брака')),
                ('comments', models.TextField(blank=True, verbose_name='Комментарии')),
                ('status', models.CharField(choices=[('started', 'Начата'), ('completed', 'Завершена'), ('paused', 'Приостановлена'), ('problem', 'Проблема')], default='started', max_length=20, verbose_name='Статус')),
                ('assignment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='manufactory.assignment', verbose_name='Задание')),
                ('brigade', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='HRM.brigade', verbose_name='Бригада')),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='HRM.sewing', verbose_name='Сотрудник')),
                ('operation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='production.technologicalmapoperation')),
                ('order_item', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='order.orderitem', verbose_name='Позиция заказа')),
            ],
            options={
                'verbose_name': 'Назначения',
                'verbose_name_plural': 'Назначения',
            },
        ),
    ]
