# Generated by Django 5.1.1 on 2024-09-18 09:13

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('manufactory', '0001_initial'),
        ('order', '0001_initial'),
        ('wms', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='assignment',
            name='order',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='order.order', verbose_name='Заказ'),
        ),
        migrations.AddField(
            model_name='assignmentemployee',
            name='assignment',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='manufactory.assignment', verbose_name='Назначение'),
        ),
        migrations.AddField(
            model_name='assignmentemployee',
            name='employee',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Сотрудник'),
        ),
        migrations.AddField(
            model_name='assignmentteam',
            name='assignment',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='manufactory.assignment', verbose_name='Назначение'),
        ),
        migrations.AddField(
            model_name='bonuspenalty',
            name='employee',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Сотрудник'),
        ),
        migrations.AddField(
            model_name='defect',
            name='assignment',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='manufactory.assignment', verbose_name='Назначение'),
        ),
        migrations.AddField(
            model_name='defect',
            name='employee',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Обнаружил'),
        ),
        migrations.AddField(
            model_name='employeehistory',
            name='assignment',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='manufactory.assignment', verbose_name='Назначение'),
        ),
        migrations.AddField(
            model_name='employeehistory',
            name='employee',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Сотрудник'),
        ),
        migrations.AddField(
            model_name='employeehistory',
            name='order',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='order.order', verbose_name='Заказ'),
        ),
        migrations.AddField(
            model_name='employeeworkcontribution',
            name='assignment',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='manufactory.assignment', verbose_name='Назначение'),
        ),
        migrations.AddField(
            model_name='employeeworkcontribution',
            name='employee',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Сотрудник'),
        ),
        migrations.AddField(
            model_name='materialrequest',
            name='assignment',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='manufactory.assignment', verbose_name='Назначение'),
        ),
        migrations.AddField(
            model_name='materialrequest',
            name='material',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='wms.product', verbose_name='Материал'),
        ),
        migrations.AddField(
            model_name='employeehistory',
            name='operation',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='manufactory.operation', verbose_name='Операция'),
        ),
        migrations.AddField(
            model_name='assignment',
            name='operation',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='manufactory.operation', verbose_name='Операция'),
        ),
        migrations.AddField(
            model_name='operationmaterial',
            name='material',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='wms.product', verbose_name='Материал'),
        ),
        migrations.AddField(
            model_name='operationmaterial',
            name='operation',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='manufactory.operation', verbose_name='Операция'),
        ),
        migrations.AddField(
            model_name='operationnorm',
            name='operation',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='manufactory.operation', verbose_name='Операция'),
        ),
        migrations.AddField(
            model_name='productionteam',
            name='members',
            field=models.ManyToManyField(to=settings.AUTH_USER_MODEL, verbose_name='Участники бригады'),
        ),
        migrations.AddField(
            model_name='assignmentteam',
            name='team',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='manufactory.productionteam', verbose_name='Бригада'),
        ),
        migrations.AddField(
            model_name='assignment',
            name='team',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='manufactory.productionteam', verbose_name='Бригада'),
        ),
        migrations.AddField(
            model_name='stage',
            name='next_stage',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='manufactory.stage', verbose_name='Следующий этап'),
        ),
        migrations.AddField(
            model_name='operation',
            name='stage',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='manufactory.stage', verbose_name='Этап'),
        ),
        migrations.AddField(
            model_name='workinterval',
            name='assignment_employee',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='manufactory.assignmentemployee', verbose_name='Назначение сотруднику'),
        ),
    ]
