# Generated by Django 5.1.1 on 2024-09-30 05:42

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manufactory', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='cutting',
            name='end_time',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Время окончания'),
        ),
        migrations.AddField(
            model_name='cutting',
            name='fabric_leftovers',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Укажите количество остатков ткани после кроя', max_digits=10, verbose_name='Остатки ткани'),
        ),
        migrations.AddField(
            model_name='cutting',
            name='fabric_waste',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Укажите количество отходов ткани (брак)', max_digits=10, verbose_name='Отходы ткани'),
        ),
        migrations.AddField(
            model_name='cutting',
            name='start_time',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='Время начала'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='cutting',
            name='status',
            field=models.CharField(choices=[('new', 'Новое'), ('in_progress', 'В работе'), ('completed', 'Выполнено'), ('paused', 'Приостановлено')], default='new', max_length=20, verbose_name='Статус'),
        ),
        migrations.AddField(
            model_name='cutting',
            name='waste_reason',
            field=models.TextField(blank=True, verbose_name='Причина отходов'),
        ),
        migrations.AlterField(
            model_name='cutting',
            name='quantity',
            field=models.PositiveIntegerField(default=0, verbose_name='Количество выкроенных изделий'),
        ),
    ]
