# Generated by Django 5.1.1 on 2024-09-18 12:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manufactory', '0002_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ActualMaterialConsumption',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Фактически использованное количество')),
            ],
        ),
        migrations.CreateModel(
            name='EmployeeContribution',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(default=0, verbose_name='Количество произведенных единиц')),
            ],
            options={
                'verbose_name': 'Вклад сотрудника',
                'verbose_name_plural': 'Вклады сотрудников',
            },
        ),
        migrations.RemoveField(
            model_name='assignmentemployee',
            name='assignment',
        ),
        migrations.RemoveField(
            model_name='assignmentemployee',
            name='employee',
        ),
        migrations.RemoveField(
            model_name='workinterval',
            name='assignment_employee',
        ),
        migrations.RemoveField(
            model_name='assignmentteam',
            name='assignment',
        ),
        migrations.RemoveField(
            model_name='assignmentteam',
            name='team',
        ),
        migrations.RemoveField(
            model_name='bonuspenalty',
            name='employee',
        ),
        migrations.RemoveField(
            model_name='employeehistory',
            name='assignment',
        ),
        migrations.RemoveField(
            model_name='employeehistory',
            name='employee',
        ),
        migrations.RemoveField(
            model_name='employeehistory',
            name='operation',
        ),
        migrations.RemoveField(
            model_name='employeehistory',
            name='order',
        ),
        migrations.RemoveField(
            model_name='employeeworkcontribution',
            name='assignment',
        ),
        migrations.RemoveField(
            model_name='employeeworkcontribution',
            name='employee',
        ),
    ]
