# Generated by Django 5.1.1 on 2024-09-30 10:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manufactory', '0002_cutting_end_time_cutting_fabric_leftovers_and_more'),
        ('production', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='assignment',
            name='current_stage',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='production.stage', verbose_name='Текущий этап'),
        ),
        migrations.AlterField(
            model_name='assignment',
            name='status',
            field=models.CharField(choices=[('in_line', 'В очереди'), ('in_progress_of_cutting', 'В процессе кроя'), ('in_process_of_sewing', 'В процессе пошива'), ('ready_for_shipment', 'Готово к отгрузке'), ('paused', 'Приостановлено')], default='new', max_length=50, verbose_name='Статус'),
        ),
    ]
