# Generated by Django 5.1.1 on 2024-09-18 12:17

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manufactory', '0003_actualmaterialconsumption_employeecontribution_and_more'),
        ('production', '0002_remove_technologicalmap_quantity_and_more'),
        ('wms', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.DeleteModel(
            name='Equipment',
        ),
        migrations.RemoveField(
            model_name='operationmaterial',
            name='material',
        ),
        migrations.RemoveField(
            model_name='operationmaterial',
            name='operation',
        ),
        migrations.RemoveField(
            model_name='operationnorm',
            name='operation',
        ),
        migrations.DeleteModel(
            name='PaymentType',
        ),
        migrations.DeleteModel(
            name='Skill',
        ),
        migrations.RemoveField(
            model_name='assignment',
            name='employee',
        ),
        migrations.RemoveField(
            model_name='assignment',
            name='end_date',
        ),
        migrations.RemoveField(
            model_name='assignment',
            name='start_date',
        ),
        migrations.RemoveField(
            model_name='defect',
            name='date_detected',
        ),
        migrations.RemoveField(
            model_name='defect',
            name='defect_type',
        ),
        migrations.RemoveField(
            model_name='defect',
            name='description',
        ),
        migrations.RemoveField(
            model_name='materialrequest',
            name='approved_quantity',
        ),
        migrations.RemoveField(
            model_name='materialrequest',
            name='is_excess',
        ),
        migrations.RemoveField(
            model_name='operation',
            name='payment_type',
        ),
        migrations.RemoveField(
            model_name='operation',
            name='piecework_rate',
        ),
        migrations.RemoveField(
            model_name='stage',
            name='next_stage',
        ),
        migrations.AddField(
            model_name='assignment',
            name='assigned_quantity',
            field=models.PositiveIntegerField(default=0, verbose_name='Назначенное количество'),
        ),
        migrations.AddField(
            model_name='assignment',
            name='completed_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Дата и время завершения работы'),
        ),
        migrations.AddField(
            model_name='assignment',
            name='completed_quantity',
            field=models.PositiveIntegerField(default=0, verbose_name='Количество произведенных единиц'),
        ),
        migrations.AddField(
            model_name='assignment',
            name='started_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Дата и время начала работы'),
        ),
        migrations.AddField(
            model_name='defect',
            name='reason',
            field=models.TextField(blank=True, verbose_name='Причина  брака'),
        ),
        migrations.AlterField(
            model_name='assignment',
            name='order',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='production.productionorder', verbose_name='Заказ'),
        ),
        migrations.AlterField(
            model_name='assignment',
            name='status',
            field=models.CharField(choices=[('new', 'Новое'), ('in_progress', 'В работе'), ('completed', 'Завершено'), ('canceled', 'Отменено')], default='new', max_length=20, verbose_name='Статус'),
        ),
        migrations.AlterField(
            model_name='defect',
            name='employee',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Сотрудник'),
        ),
        migrations.AlterField(
            model_name='defect',
            name='quantity',
            field=models.PositiveIntegerField(default=0, verbose_name='Количество  бракованных  изделий'),
        ),
        migrations.AlterField(
            model_name='materialrequest',
            name='material',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='wms.product', verbose_name='Материал'),
        ),
        migrations.AlterField(
            model_name='materialrequest',
            name='status',
            field=models.CharField(choices=[('new', 'Новая'), ('approved', 'Одобрена'), ('rejected', 'Отклонена'), ('partially_issued', 'Частично выдана'), ('issued', 'Выдана')], default='new', max_length=20, verbose_name='Статус'),
        ),
        migrations.AddField(
            model_name='actualmaterialconsumption',
            name='assignment',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='manufactory.assignment', verbose_name='Назначение'),
        ),
        migrations.AddField(
            model_name='actualmaterialconsumption',
            name='material',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='wms.product', verbose_name='Материал'),
        ),
        migrations.AddField(
            model_name='employeecontribution',
            name='assignment',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='manufactory.assignment', verbose_name='Назначение'),
        ),
        migrations.AddField(
            model_name='employeecontribution',
            name='employee',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Сотрудник'),
        ),
        migrations.DeleteModel(
            name='AssignmentEmployee',
        ),
        migrations.DeleteModel(
            name='WorkInterval',
        ),
        migrations.DeleteModel(
            name='AssignmentTeam',
        ),
        migrations.DeleteModel(
            name='BonusPenalty',
        ),
        migrations.DeleteModel(
            name='EmployeeHistory',
        ),
        migrations.DeleteModel(
            name='EmployeeWorkContribution',
        ),
        migrations.DeleteModel(
            name='OperationMaterial',
        ),
        migrations.DeleteModel(
            name='OperationNorm',
        ),
    ]
