# Generated by Django 5.1.1 on 2024-09-19 07:53

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('manufactory', '0004_delete_equipment_remove_operationmaterial_material_and_more'),
        ('order', '0002_initial'),
        ('production', '0002_remove_technologicalmap_quantity_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Brigade',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True, verbose_name='Название бригады')),
            ],
        ),
        migrations.CreateModel(
            name='OperationLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(verbose_name='Количество')),
                ('start_time', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Время начала')),
                ('end_time', models.DateTimeField(blank=True, null=True, verbose_name='Время окончания')),
            ],
            options={
                'verbose_name': 'Запись журнала операций',
                'verbose_name_plural': 'Журнал операций',
            },
        ),
        migrations.RemoveField(
            model_name='actualmaterialconsumption',
            name='assignment',
        ),
        migrations.RemoveField(
            model_name='actualmaterialconsumption',
            name='material',
        ),
        migrations.RemoveField(
            model_name='defect',
            name='assignment',
        ),
        migrations.RemoveField(
            model_name='defect',
            name='employee',
        ),
        migrations.RemoveField(
            model_name='employeecontribution',
            name='assignment',
        ),
        migrations.RemoveField(
            model_name='employeecontribution',
            name='employee',
        ),
        migrations.RemoveField(
            model_name='operation',
            name='stage',
        ),
        migrations.AlterField(
            model_name='assignment',
            name='operation',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='production.technologicalmapoperation', verbose_name='Операция'),
        ),
        migrations.RemoveField(
            model_name='productionteam',
            name='members',
        ),
        migrations.RemoveField(
            model_name='assignment',
            name='team',
        ),
        migrations.AlterModelOptions(
            name='assignment',
            options={},
        ),
        migrations.AlterModelOptions(
            name='materialrequest',
            options={'verbose_name': 'Заявка на материал', 'verbose_name_plural': 'Заявки на материалы'},
        ),
        migrations.RemoveField(
            model_name='assignment',
            name='assigned_quantity',
        ),
        migrations.RemoveField(
            model_name='assignment',
            name='completed_at',
        ),
        migrations.RemoveField(
            model_name='assignment',
            name='order',
        ),
        migrations.RemoveField(
            model_name='assignment',
            name='started_at',
        ),
        migrations.RemoveField(
            model_name='materialrequest',
            name='request_date',
        ),
        migrations.AddField(
            model_name='assignment',
            name='end_date',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Дата окончания'),
        ),
        migrations.AddField(
            model_name='assignment',
            name='group',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='auth.group', verbose_name='Группа'),
        ),
        migrations.AddField(
            model_name='assignment',
            name='order_item',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='order.orderitem', verbose_name='Позиция заказа'),
        ),
        migrations.AddField(
            model_name='assignment',
            name='quantity',
            field=models.PositiveIntegerField(default=0, verbose_name='Количество'),
        ),
    ]
