# Generated by Django 5.1.1 on 2024-09-19 07:53

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manufactory', '0005_brigade_operationlog_and_more'),
        ('production', '0003_operation_stage_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='assignment',
            name='stage',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='production.stage', verbose_name='Этап производства'),
        ),
        migrations.AddField(
            model_name='assignment',
            name='start_date',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Дата начала'),
        ),
        migrations.AlterField(
            model_name='assignment',
            name='completed_quantity',
            field=models.PositiveIntegerField(default=0, verbose_name='Выполнено'),
        ),
        migrations.AlterField(
            model_name='assignment',
            name='status',
            field=models.CharField(choices=[('new', 'Новое'), ('in_progress', 'В работе'), ('completed', 'Выполнено'), ('paused', 'Приостановлено')], default='new', max_length=20, verbose_name='Статус'),
        ),
        migrations.AlterField(
            model_name='materialrequest',
            name='assignment',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='manufactory.assignment', verbose_name='Задание'),
        ),
        migrations.AlterField(
            model_name='materialrequest',
            name='material',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='production.technologicalmapmaterial', verbose_name='Материал'),
        ),
        migrations.AlterField(
            model_name='materialrequest',
            name='status',
            field=models.CharField(choices=[('requested', 'Запрошено'), ('partially_issued', 'Частично выдано'), ('issued', 'Выдано'), ('canceled', 'Отменено')], default='requested', max_length=20, verbose_name='Статус'),
        ),
        migrations.AddField(
            model_name='operationlog',
            name='assignment',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='manufactory.assignment', verbose_name='Задание'),
        ),
        migrations.AddField(
            model_name='operationlog',
            name='employee',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Сотрудник'),
        ),
        migrations.AddField(
            model_name='operationlog',
            name='operation',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='production.technologicalmapoperation', verbose_name='Операция'),
        ),
        migrations.DeleteModel(
            name='ActualMaterialConsumption',
        ),
        migrations.DeleteModel(
            name='Defect',
        ),
        migrations.DeleteModel(
            name='EmployeeContribution',
        ),
        migrations.DeleteModel(
            name='Stage',
        ),
        migrations.DeleteModel(
            name='Operation',
        ),
        migrations.DeleteModel(
            name='ProductionTeam',
        ),
    ]
