# Generated by Django 5.1.1 on 2024-09-19 08:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HRM', '0003_brigade_employee_brigades'),
        ('manufactory', '0006_assignment_stage_assignment_start_date_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Brigade',
        ),
        migrations.RemoveField(
            model_name='assignment',
            name='group',
        ),
        migrations.AddField(
            model_name='assignment',
            name='brigade',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='HRM.brigade', verbose_name='Бригада'),
        ),
    ]
