# Generated by Django 5.1.1 on 2024-09-19 09:25

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manufactory', '0007_delete_brigade_remove_assignment_group_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='operationlog',
            name='duration',
            field=models.DurationField(blank=True, null=True, verbose_name='Длительность'),
        ),
        migrations.AddField(
            model_name='operationlog',
            name='status',
            field=models.CharField(choices=[('started', 'Начата'), ('completed', 'Завершена'), ('paused', 'Приостановлена'), ('problem', 'Проблема')], default='started', max_length=20, verbose_name='Статус'),
        ),
        migrations.CreateModel(
            name='Cleaning',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity_cleaned', models.PositiveIntegerField(default=0, verbose_name='Количество очищенных изделий')),
                ('start_time', models.DateTimeField(auto_now_add=True, verbose_name='Время начала')),
                ('end_time', models.DateTimeField(blank=True, null=True, verbose_name='Время окончания')),
                ('assignment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='manufactory.assignment', verbose_name='Задание')),
                ('employee', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Очиститель')),
            ],
        ),
        migrations.CreateModel(
            name='Cutting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity_cut', models.PositiveIntegerField(default=0, verbose_name='Количество выкроенных изделий')),
                ('fabric_leftovers', models.DecimalField(decimal_places=2, default=0, help_text='Укажите количество остатков ткани после кроя', max_digits=10, verbose_name='Остатки ткани')),
                ('fabric_waste', models.DecimalField(decimal_places=2, default=0, help_text='Укажите количество отходов ткани (брак)', max_digits=10, verbose_name='Отходы ткани')),
                ('waste_reason', models.TextField(blank=True, verbose_name='Причина отходов')),
                ('start_time', models.DateTimeField(auto_now_add=True, verbose_name='Время начала')),
                ('end_time', models.DateTimeField(blank=True, null=True, verbose_name='Время окончания')),
                ('assignment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='manufactory.assignment', verbose_name='Задание')),
                ('employee', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Кройщик')),
            ],
            options={
                'verbose_name': 'Кройка',
                'verbose_name_plural': 'Кройка',
            },
        ),
        migrations.CreateModel(
            name='Ironing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity_ironed', models.PositiveIntegerField(default=0, verbose_name='Количество отутюженных изделий')),
                ('start_time', models.DateTimeField(auto_now_add=True, verbose_name='Время начала')),
                ('end_time', models.DateTimeField(blank=True, null=True, verbose_name='Время окончания')),
                ('assignment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='manufactory.assignment', verbose_name='Задание')),
                ('employee', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Утюжильщик')),
            ],
        ),
        migrations.CreateModel(
            name='Packing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity_packed', models.PositiveIntegerField(default=0, verbose_name='Количество упакованных изделий')),
                ('start_time', models.DateTimeField(auto_now_add=True, verbose_name='Время начала')),
                ('end_time', models.DateTimeField(blank=True, null=True, verbose_name='Время окончания')),
                ('assignment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='manufactory.assignment', verbose_name='Задание')),
                ('employee', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Упаковщик')),
            ],
        ),
    ]
