# Generated by Django 5.1.1 on 2024-09-19 11:17

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manufactory', '0008_operationlog_duration_operationlog_status_cleaning_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cleaning',
            options={'verbose_name': 'Очистка', 'verbose_name_plural': 'Очистка'},
        ),
        migrations.AlterModelOptions(
            name='ironing',
            options={'verbose_name': 'Утюжки', 'verbose_name_plural': 'Утюжки'},
        ),
        migrations.AlterModelOptions(
            name='packing',
            options={'verbose_name': 'Упаковка', 'verbose_name_plural': 'Упаковка'},
        ),
        migrations.CreateModel(
            name='Sewing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity_sewn', models.PositiveIntegerField(default=0, verbose_name='Количество пошитых изделий')),
                ('start_time', models.DateTimeField(auto_now_add=True, verbose_name='Время начала')),
                ('end_time', models.DateTimeField(blank=True, null=True, verbose_name='Время окончания')),
                ('assignment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='manufactory.assignment', verbose_name='Задание')),
                ('employee', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Швея')),
            ],
            options={
                'verbose_name': 'Пошив',
                'verbose_name_plural': 'Пошив',
            },
        ),
    ]
