# Generated by Django 5.1.1 on 2024-09-25 12:19

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manufactory', '0010_remove_assignment_brigade_assignment_user'),
        ('production', '0008_rename_cost_price_productionitem__cost_price'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cutting',
            name='assignment',
        ),
        migrations.RemoveField(
            model_name='cutting',
            name='employee',
        ),
        migrations.RemoveField(
            model_name='ironing',
            name='assignment',
        ),
        migrations.RemoveField(
            model_name='ironing',
            name='employee',
        ),
        migrations.RemoveField(
            model_name='packing',
            name='assignment',
        ),
        migrations.RemoveField(
            model_name='packing',
            name='employee',
        ),
        migrations.RemoveField(
            model_name='sewing',
            name='assignment',
        ),
        migrations.RemoveField(
            model_name='sewing',
            name='employee',
        ),
        migrations.CreateModel(
            name='Defect',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(verbose_name='Количество  бракованных  изделий')),
                ('description', models.TextField(blank=True, verbose_name='Описание  брака')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата  создания')),
                ('assignment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='manufactory.assignment', verbose_name='Задание')),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Сотрудник')),
                ('operation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='production.technologicalmapoperation', verbose_name='Операция')),
            ],
            options={
                'verbose_name': 'Брак',
                'verbose_name_plural': 'Брак',
            },
        ),
        migrations.DeleteModel(
            name='Cleaning',
        ),
        migrations.DeleteModel(
            name='Cutting',
        ),
        migrations.DeleteModel(
            name='Ironing',
        ),
        migrations.DeleteModel(
            name='Packing',
        ),
        migrations.DeleteModel(
            name='Sewing',
        ),
    ]
