# Generated by Django 5.1.1 on 2024-09-27 07:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HRM', '0012_brigade_remove_employee_salary_employee_hourly_rate_and_more'),
        ('manufactory', '0011_remove_cutting_assignment_remove_cutting_employee_and_more'),
        ('order', '0004_remove_order_total_quantity_remove_orderitem_price_and_more'),
        ('production', '0008_rename_cost_price_productionitem__cost_price'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='assignment',
            name='operation',
        ),
        migrations.RemoveField(
            model_name='assignment',
            name='stage',
        ),
        migrations.RemoveField(
            model_name='assignment',
            name='user',
        ),
        migrations.AddField(
            model_name='assignment',
            name='brigade',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='HRM.brigade', verbose_name='Бригада'),
        ),
        migrations.AddField(
            model_name='operationlog',
            name='comments',
            field=models.TextField(blank=True, verbose_name='Комментарии'),
        ),
        migrations.AddField(
            model_name='operationlog',
            name='defect_quantity',
            field=models.PositiveIntegerField(default=0, verbose_name='Количество брака'),
        ),
        migrations.AlterField(
            model_name='assignment',
            name='order_item',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='order.orderitem', verbose_name='Позиция заказа'),
        ),
        migrations.AlterField(
            model_name='operationlog',
            name='operation',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='production.technologicalmapoperation'),
        ),
    ]
