# Generated by Django 5.1.1 on 2024-09-27 09:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HRM', '0014_alter_sewing_code'),
        ('manufactory', '0012_remove_assignment_operation_remove_assignment_stage_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assignment',
            name='quantity',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Количество'),
        ),
        migrations.AlterField(
            model_name='operationlog',
            name='employee',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='HRM.sewing', verbose_name='Сотрудник'),
        ),
    ]
