# Generated by Django 5.1.1 on 2024-10-05 12:04

import django.contrib.auth.models
import django.contrib.auth.validators
import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='Branch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='Название филиала')),
                ('address', models.CharField(blank=True, max_length=255, verbose_name='Адрес')),
                ('phone', models.CharField(blank=True, max_length=20, verbose_name='Телефон')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='Email')),
            ],
            options={
                'verbose_name': 'Филиал',
                'verbose_name_plural': 'Филиалы',
            },
        ),
        migrations.CreateModel(
            name='Brigade',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
            options={
                'verbose_name': 'Бригада',
                'verbose_name_plural': 'Бригада',
            },
        ),
        migrations.CreateModel(
            name='NfcTag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uid', models.CharField(max_length=255, unique=True, verbose_name='UID метки')),
            ],
            options={
                'verbose_name': 'NFC',
                'verbose_name_plural': 'NFC',
            },
        ),
        migrations.CreateModel(
            name='Sewing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('code', models.DecimalField(decimal_places=0, max_digits=9999)),
            ],
            options={
                'verbose_name': 'Швея',
                'verbose_name_plural': 'Швея',
            },
        ),
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='email address')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('position', models.CharField(max_length=100, verbose_name='Должность')),
                ('hire_date', models.DateField(blank=True, null=True, verbose_name='Дата приема на работу')),
                ('payment_type', models.CharField(choices=[('piecework', 'Сдельная оплата'), ('salary', 'Фиксированный оклад')], default='salary', max_length=20, verbose_name='Тип оплаты труда')),
                ('hourly_rate', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=8, null=True, verbose_name='Почасовая ставка')),
                ('piece_rate', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=8, null=True, verbose_name='Ставка за штуку')),
                ('is_active', models.BooleanField(default=True, verbose_name='Работает в данный момент')),
            ],
            options={
                'verbose_name': 'Сотрудник',
                'verbose_name_plural': 'Сотрудники',
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='Permission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('can_view', models.BooleanField(default=False, verbose_name='Просмотр')),
                ('can_create', models.BooleanField(default=False, verbose_name='Создание')),
                ('can_edit', models.BooleanField(default=False, verbose_name='Редактирование')),
                ('can_delete', models.BooleanField(default=False, verbose_name='Удаление')),
                ('content_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hrm_permissions', to='contenttypes.contenttype')),
            ],
            options={
                'verbose_name': 'Разрешение',
                'verbose_name_plural': 'Разрешения',
            },
        ),
        migrations.CreateModel(
            name='Role',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='Название роли')),
                ('permissions', models.ManyToManyField(to='HRM.permission', verbose_name='Права')),
            ],
            options={
                'verbose_name': 'Роль',
                'verbose_name_plural': 'Роль',
            },
        ),
    ]
