# Generated by Django 5.1.1 on 2024-10-03 07:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HRM', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='payment_type',
            field=models.CharField(choices=[('piecework', 'Сдельная оплата'), ('salary', 'Фиксированный оклад')], default='salary', max_length=20, verbose_name='Тип оплаты труда'),
        ),
    ]
