# Generated by Django 5.1.1 on 2024-09-19 08:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HRM', '0002_remove_employee_department_delete_department'),
    ]

    operations = [
        migrations.CreateModel(
            name='Brigade',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True, verbose_name='Название бригады')),
            ],
        ),
        migrations.AddField(
            model_name='employee',
            name='brigades',
            field=models.ManyToManyField(blank=True, to='HRM.brigade', verbose_name='Бригады'),
        ),
    ]
