# Generated by Django 5.1.1 on 2024-09-24 12:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('HRM', '0003_brigade_employee_brigades'),
        ('manufactory', '0010_remove_assignment_brigade_assignment_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employee',
            name='brigades',
        ),
        migrations.DeleteModel(
            name='Brigade',
        ),
    ]
