# Generated by Django 5.1.1 on 2024-09-24 13:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('HRM', '0004_remove_employee_brigades_delete_brigade'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='employee',
            options={'verbose_name': 'user', 'verbose_name_plural': 'users'},
        ),
    ]
