# Generated by Django 5.1.1 on 2024-09-24 13:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HRM', '0005_alter_employee_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='permission',
            name='role',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='permissions', to='HRM.role', verbose_name='Роль'),
        ),
    ]
