# Generated by Django 5.1.1 on 2024-09-24 13:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HRM', '0007_alter_employee_options_alter_permission_role'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='employee',
            options={'verbose_name': 'user', 'verbose_name_plural': 'users'},
        ),
        migrations.AddField(
            model_name='role',
            name='can_create',
            field=models.BooleanField(default=False, verbose_name='Создание'),
        ),
        migrations.AddField(
            model_name='role',
            name='can_delete',
            field=models.BooleanField(default=False, verbose_name='Удаление'),
        ),
        migrations.AddField(
            model_name='role',
            name='can_edit',
            field=models.BooleanField(default=False, verbose_name='Редактирование'),
        ),
        migrations.AddField(
            model_name='role',
            name='can_view',
            field=models.BooleanField(default=False, verbose_name='Просмотр'),
        ),
    ]
