# Generated by Django 5.1.1 on 2024-09-24 13:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('HRM', '0008_alter_employee_options_role_can_create_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='employee',
            options={'verbose_name': 'Сотрудник', 'verbose_name_plural': 'Сотрудники'},
        ),
        migrations.RemoveField(
            model_name='role',
            name='can_create',
        ),
        migrations.RemoveField(
            model_name='role',
            name='can_delete',
        ),
        migrations.RemoveField(
            model_name='role',
            name='can_edit',
        ),
        migrations.RemoveField(
            model_name='role',
            name='can_view',
        ),
    ]
