# Generated by Django 5.1.1 on 2024-09-25 11:05

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HRM', '0009_alter_employee_options_remove_role_can_create_and_more'),
        ('production', '0008_rename_cost_price_productionitem__cost_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='allowed_stages',
            field=models.ManyToManyField(blank=True, to='production.stage', verbose_name='Разрешенные  этапы'),
        ),
        migrations.CreateModel(
            name='NfcTag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uid', models.CharField(max_length=255, unique=True, verbose_name='UID метки')),
                ('employee', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Сотрудник')),
            ],
        ),
    ]
