# Generated by Django 5.1.1 on 2024-09-26 11:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HRM', '0010_employee_allowed_stages_nfctag'),
        ('auth', '0012_alter_user_first_name_max_length'),
        ('production', '0008_rename_cost_price_productionitem__cost_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='role',
            name='group',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='auth.group', verbose_name='Группа'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='allowed_stages',
            field=models.ManyToManyField(blank=True, to='production.stage', verbose_name='Разрешенные этапы'),
        ),
        migrations.AlterField(
            model_name='role',
            name='name',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
