# Generated by Django 5.1.1 on 2024-09-27 07:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HRM', '0011_role_group_alter_employee_allowed_stages_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Brigade',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.RemoveField(
            model_name='employee',
            name='salary',
        ),
        migrations.AddField(
            model_name='employee',
            name='hourly_rate',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=8, null=True, verbose_name='Почасовая ставка'),
        ),
        migrations.AddField(
            model_name='employee',
            name='payment_type',
            field=models.CharField(choices=[('piecework', 'Сдельная'), ('salary', 'Повременная')], default='piecework', max_length=20, verbose_name='Тип оплаты труда'),
        ),
        migrations.AddField(
            model_name='employee',
            name='piece_rate',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=8, null=True, verbose_name='Ставка за штуку'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='Работает в данный момент'),
        ),
        migrations.DeleteModel(
            name='Payroll',
        ),
    ]
