# Generated by Django 5.1.1 on 2024-09-27 08:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HRM', '0012_brigade_remove_employee_salary_employee_hourly_rate_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Sewing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('code', models.DecimalField(decimal_places=5, max_digits=99999)),
            ],
        ),
    ]
