# Generated by Django 5.1.1 on 2024-09-27 09:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HRM', '0013_sewing'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sewing',
            name='code',
            field=models.DecimalField(decimal_places=0, max_digits=9999),
        ),
    ]
