# Generated by Django 5.1.1 on 2024-10-05 12:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Counterparty',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Название')),
                ('inn', models.CharField(blank=True, max_length=20, verbose_name='ИНН')),
                ('address', models.TextField(blank=True, verbose_name='Адрес')),
                ('phone', models.CharField(blank=True, max_length=20, verbose_name='Телефон')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='Email')),
                ('contact_name', models.CharField(blank=True, max_length=255, verbose_name='Контактное лицо')),
                ('description', models.TextField(blank=True, verbose_name='Комментарий')),
                ('counterparty_type', models.CharField(choices=[('supplier', 'Поставщик'), ('customer', 'Покупатель')], default='supplier', max_length=10, verbose_name='Тип контрагента')),
            ],
            options={
                'verbose_name': 'Контрагент',
                'verbose_name_plural': 'Контрагент',
            },
        ),
    ]
