# Generated by Django 5.1.1 on 2024-10-03 07:59

import datetime
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('order', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Counterparty',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Название')),
                ('counterparty_type', models.CharField(choices=[('supplier', 'Поставщик'), ('customer', 'Покупатель')], default='supplier', max_length=10, verbose_name='Тип контрагента')),
            ],
        ),
        migrations.CreateModel(
            name='Payroll',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Account',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=20, unique=True, verbose_name='Код счета')),
                ('name', models.CharField(max_length=255, verbose_name='Название счета')),
                ('account_type', models.CharField(choices=[('active', 'Активный'), ('passive', 'Пассивный'), ('active_passive', 'Активно-пассивный')], default='active', max_length=20, verbose_name='Тип счета')),
                ('description', models.TextField(blank=True, verbose_name='Описание')),
                ('parent_account', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='accounting.account', verbose_name='Родительский счет')),
            ],
            options={
                'verbose_name': 'Счет',
                'verbose_name_plural': 'План счетов',
            },
        ),
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('document_type', models.CharField(choices=[('invoice', 'Счет-фактура'), ('waybill', 'Накладная'), ('act', 'Акт')], max_length=20, verbose_name='Тип документа')),
                ('number', models.CharField(max_length=50, verbose_name='Номер')),
                ('date', models.DateField(verbose_name='Дата')),
                ('counterparty', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='accounting.counterparty', verbose_name='Контрагент')),
            ],
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(default=datetime.date.today, verbose_name='Дата')),
                ('transaction_type', models.CharField(choices=[('other', 'Другое'), ('salary', 'Зарплата'), ('material_purchase', 'Покупка материалов'), ('material_write_off', 'Списание материалов'), ('product_sale', 'Продажа продукции'), ('cash_receipt', 'Поступление денежных средств'), ('cash_disbursement', 'Выплата денежных средств')], default='other', max_length=50, verbose_name='Тип операции')),
                ('description', models.CharField(max_length=255, verbose_name='Описание')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL, verbose_name='Создано пользователем')),
                ('document', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='accounting.document', verbose_name='Документ')),
                ('order', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='order.order', verbose_name='Заказ')),
            ],
            options={
                'verbose_name': 'Хозяйственная операция',
                'verbose_name_plural': 'Хозяйственные операции',
            },
        ),
        migrations.CreateModel(
            name='TransactionLine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('debit', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Дебет')),
                ('credit', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Кредит')),
                ('line_description', models.CharField(blank=True, max_length=255, verbose_name='Описание строки')),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='accounting.account', verbose_name='Счет')),
                ('transaction', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lines', to='accounting.transaction', verbose_name='Операция')),
            ],
            options={
                'verbose_name': 'Строка операции',
                'verbose_name_plural': 'Строки операции',
            },
        ),
    ]
