# Generated by Django 5.1.1 on 2024-10-05 12:04

import datetime
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('CRM', '0001_initial'),
        ('wms', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Account',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=20, unique=True, verbose_name='Код счета')),
                ('name', models.CharField(max_length=255, verbose_name='Название счета')),
                ('account_type', models.CharField(choices=[('active', 'Активный'), ('passive', 'Пассивный'), ('active_passive', 'Активно-пассивный'), ('income', 'Доходы'), ('expense', 'Затраты')], default='active', max_length=20, verbose_name='Тип счета')),
                ('description', models.TextField(blank=True, verbose_name='Описание')),
                ('parent_account', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='accounting.account', verbose_name='Родительский счет')),
            ],
            options={
                'verbose_name': 'Счет',
                'verbose_name_plural': 'План счетов',
            },
        ),
        migrations.CreateModel(
            name='AdvanceAmount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Сумма')),
                ('period_start', models.DateField(default=datetime.date.today, verbose_name='Начало периода')),
                ('period_end', models.DateField(null=True, verbose_name='Конец периода')),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('document_type', models.CharField(choices=[('invoice', 'Счет-фактура'), ('waybill', 'Накладная'), ('act', 'Акт')], max_length=20, verbose_name='Тип документа')),
                ('number', models.CharField(max_length=50, verbose_name='Номер')),
                ('date', models.DateField(verbose_name='Дата')),
                ('counterparty', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='CRM.counterparty', verbose_name='Контрагент')),
            ],
            options={
                'verbose_name': 'Документы',
                'verbose_name_plural': 'Документы',
            },
        ),
        migrations.CreateModel(
            name='TransactionType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Название Транзакции')),
                ('description', models.TextField(blank=True, verbose_name='Описание')),
                ('parent_transaction', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='accounting.transactiontype', verbose_name='Родительский счет')),
            ],
            options={
                'verbose_name': 'Тип транзакции',
                'verbose_name_plural': 'Тип транзакции',
            },
        ),
        migrations.CreateModel(
            name='Purchase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Количество')),
                ('amount', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Сумма')),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounting.account')),
                ('transaction_type', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='accounting.transactiontype', verbose_name='Названия')),
            ],
            options={
                'verbose_name': 'Покупка',
                'verbose_name_plural': 'Покупка',
            },
        ),
        migrations.CreateModel(
            name='Expense',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Сумма')),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounting.account', verbose_name='Счет')),
                ('operation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounting.transactiontype', verbose_name='Операция')),
            ],
            options={
                'verbose_name': 'Расходы',
                'verbose_name_plural': 'Расходы',
            },
        ),
        migrations.CreateModel(
            name='WriteOff',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Количество')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL, verbose_name='Создано пользователем')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='wms.product', verbose_name='Товар')),
                ('transaction_type', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='accounting.transactiontype', verbose_name='Названия')),
                ('warehouse', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='wms.warehouse', verbose_name='Склад')),
            ],
            options={
                'verbose_name': 'Списание',
                'verbose_name_plural': 'Списание',
            },
        ),
    ]
