# Generated by Django 5.1.1 on 2024-10-03 08:51

import datetime
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HRM', '0002_alter_employee_payment_type'),
        ('accounting', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='payroll',
            options={'verbose_name': 'Зарплатная ведомость', 'verbose_name_plural': 'Зарплатные ведомости'},
        ),
        migrations.AddField(
            model_name='payroll',
            name='advance_amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Аванс'),
        ),
        migrations.AddField(
            model_name='payroll',
            name='bonus',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Премия'),
        ),
        migrations.AddField(
            model_name='payroll',
            name='employee',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Сотрудник'),
        ),
        migrations.AddField(
            model_name='payroll',
            name='other_allowances',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Прочие надбавки'),
        ),
        migrations.AddField(
            model_name='payroll',
            name='other_deductions',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Прочие вычеты'),
        ),
        migrations.AddField(
            model_name='payroll',
            name='overtime_hours',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5, verbose_name='Сверхурочные часы'),
        ),
        migrations.AddField(
            model_name='payroll',
            name='overtime_rate',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=8, verbose_name='Ставка за сверхурочные'),
        ),
        migrations.AddField(
            model_name='payroll',
            name='paid',
            field=models.BooleanField(default=False, verbose_name='Выплачено'),
        ),
        migrations.AddField(
            model_name='payroll',
            name='period_end',
            field=models.DateField(null=True, verbose_name='Конец периода'),
        ),
        migrations.AddField(
            model_name='payroll',
            name='period_start',
            field=models.DateField(default=datetime.date.today, verbose_name='Начало периода'),
        ),
        migrations.AddField(
            model_name='payroll',
            name='piecework_amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Сдельная оплата'),
        ),
        migrations.AddField(
            model_name='payroll',
            name='salary_amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Оклад за период'),
        ),
        migrations.AddField(
            model_name='payroll',
            name='sewing_employee',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='HRM.sewing', verbose_name='Сотрудник швеии'),
        ),
        migrations.AddField(
            model_name='payroll',
            name='social_security',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Соц. отчисления'),
        ),
        migrations.AddField(
            model_name='payroll',
            name='taxes',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Налоги'),
        ),
        migrations.AddField(
            model_name='payroll',
            name='total_accrued',
            field=models.DecimalField(decimal_places=2, default=0, editable=False, max_digits=10, verbose_name='Итого начислено'),
        ),
        migrations.AddField(
            model_name='payroll',
            name='total_amount',
            field=models.DecimalField(decimal_places=2, default=0, editable=False, max_digits=10, verbose_name='Итого к выплате'),
        ),
        migrations.AddField(
            model_name='payroll',
            name='total_deductions',
            field=models.DecimalField(decimal_places=2, default=0, editable=False, max_digits=10, verbose_name='Итого удержано'),
        ),
    ]
