# Generated by Django 5.1.1 on 2024-10-03 10:15

import datetime
import django.db.models.deletion
import wms.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0002_alter_payroll_options_payroll_advance_amount_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='payroll',
            name='advance_amount',
        ),
        migrations.RemoveField(
            model_name='payroll',
            name='piecework_amount',
        ),
        migrations.RemoveField(
            model_name='payroll',
            name='sewing_employee',
        ),
        migrations.AlterField(
            model_name='payroll',
            name='taxes',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name=wms.models.VAT),
        ),
        migrations.CreateModel(
            name='AdvanceAmount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Сумма')),
                ('period_start', models.DateField(default=datetime.date.today, verbose_name='Начало периода')),
                ('period_end', models.DateField(null=True, verbose_name='Конец периода')),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
