# Generated by Django 5.1.1 on 2024-10-05 12:04

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('CRM', '0001_initial'),
        ('production', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Названия')),
                ('uuid', models.CharField(blank=True, max_length=50, verbose_name='Номер заказа')),
                ('photo', models.ImageField(blank=True, null=True, upload_to='order_photos/', verbose_name='Фотография')),
                ('order_date', models.DateTimeField(auto_now_add=True, verbose_name='Дата заказа')),
                ('due_date', models.DateField(verbose_name='Срок исполнения')),
                ('order_type', models.CharField(choices=[('retail', 'Розничный'), ('wholesale', 'Оптовый'), ('individual', 'Индивидуальный пошив')], max_length=50, null=True, verbose_name='Тип заказа')),
                ('priority', models.CharField(choices=[('high', 'Высокий'), ('medium', 'Средний'), ('low', 'Низкий')], default='medium', max_length=10, verbose_name='Приоритет')),
                ('sales_channel', models.CharField(blank=True, max_length=50, verbose_name='Канал продаж')),
                ('contact_person', models.CharField(blank=True, max_length=255, verbose_name='Контактное лицо')),
                ('delivery_method', models.CharField(blank=True, choices=[('courier', 'Курьер'), ('pickup', 'Самовывоз'), ('post', 'Почта России')], max_length=50, verbose_name='Способ доставки')),
                ('delivery_address', models.TextField(blank=True, verbose_name='Адрес доставки')),
                ('prepayment', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Предоплата')),
                ('expected_payment_date', models.DateField(blank=True, null=True, verbose_name='Ожидаемая дата оплаты')),
                ('discount', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Скидка')),
                ('planned_production_start', models.DateField(blank=True, null=True, verbose_name='Планируемая дата начала производства')),
                ('planned_shipment_date', models.DateField(blank=True, null=True, verbose_name='Планируемая дата отгрузки')),
                ('status', models.CharField(choices=[('new', 'Новый'), ('in_progress', 'В обработке'), ('completed', 'Выполнен'), ('canceled', 'Отменен')], default='new', max_length=20, verbose_name='Статус')),
                ('total_amount', models.DecimalField(decimal_places=2, default=0, editable=False, max_digits=10, verbose_name='Общая сумма')),
                ('comments', models.TextField(blank=True, verbose_name='Комментарии')),
                ('total_cost', models.DecimalField(decimal_places=2, default=0, editable=False, max_digits=10, verbose_name='Общая стоимость')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Создан')),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='CRM.counterparty', verbose_name='Клиент')),
            ],
            options={
                'verbose_name': 'Заказы',
                'verbose_name_plural': 'Заказы',
            },
        ),
        migrations.CreateModel(
            name='OrderItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(verbose_name='Количество')),
                ('size', models.CharField(max_length=50, verbose_name='Размер')),
                ('cost_price', models.DecimalField(decimal_places=2, default=0, editable=False, max_digits=10, verbose_name='Себестоимость')),
                ('color', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='production.color', verbose_name='Цвет')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='order_items', to='order.order')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='production.productionitem', verbose_name='Товар')),
            ],
            options={
                'verbose_name': 'Пункты заказа',
            },
        ),
    ]
